name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Install Build Dependencies
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S cmake ninja git curl zip unzip tar verilator

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: cmake . -G Ninja

      - name: Build
        run: cmake --build . --config Release
